### ISSUE TITLE
What would be a common use case of paper_trail?

### ISSUE THREAD

**Issue by microSoftware** [izelnakri/paper_trail#105]
Hi, does this library allow you to do like the "undo" feature in Google documents and where you have access to all the modification history?

Or is it more devops focused? for example by reversing to previous database values if something goes wrong

Thanks

**Comment by izelnakri** [comment]
Hi @microSoftware , it can do both depending on how you store your models versions(and their relationship models). It is not particularly optimized for text diffs, it stores the complete text when there is a change in the field. However, I would be interested in reviewing/merging that feature if we can implement well enough.
