### ISSUE TITLE
Question on embeds_many

### ISSUE THREAD

**Issue by bumbus** [izelnakri/paper_trail#127]
Hi,
I am not sure, if I am using things wrong, or if this is the wanted behaviour.

I have a schema which `embeds_many(:entities, Entity, on_replace: :delete)`.
In my update changeset I do `cast_embed(:entities, with: &Entity.update_changeset/2)`.

This results in a version like this:

```
%PaperTrail.Version{
  __meta__: #Ecto.Schema.Metadata<:loaded, "versions">,
  event: "update",
  id: 165,
  inserted_at: ~U[2021-01-20 13:03:08Z],
  item_changes: %{
    "entities" => [
      %{
        "id" => nil,
        "language" => nil,
        "path" => nil,
        "value" => "UPDATED_VALUE"
      },
      %{"id" => nil, "language" => nil, "path" => nil, "value" => nil},
      %{"id" => nil, "language" => nil, "path" => nil, "value" => nil},
      %{"id" => nil, "language" => nil, "path" => nil, "value" => nil}
    ]
  },
  item_id: "a9c5fb77-3af7-406d-b9dd-1e5fe7266d16",
  item_type: "Document",
  meta: nil,
  origin: nil,
  originator_id: nil
}
```
I am wondering, why unchanged entities are listed in `item_changes`.
And somehow it would be helpful to also track the id of the changed entity.
Is there a way to achieve this somehow?

Any feedback is very welcome.

**Comment by maennchen** [comment]
@bumbus Currently the changes are tracked by checking the `Ecto.Changeset` `changes` field recursively.

If the changeset lists something as a change, it will be serialized as well.

Can you inspect the changeset before the update?

**Comment by izelnakri** [comment]
@bumbus we currently do one level-deep change tracking as this is what Ecto Changesets use. 

I don't think its a good idea to implement deep nested attribute/value tracking, it complicates this library and will make our operations slower. Instead please find another way to track your nested objects, perhaps by removing the embeds/moving it to another table in the db.

**Comment by bumbus** [comment]
@maennchen @izelnakri 
Thanks for reply. At the moment JSONB operations (e.g. updating one field in a embeds_many, jsonb_set) does not seem to  be well supported by ecto changeset. So it makes sense that it won't work properly with a change tracker that relies on changesets.
Would it be possible to track changes (insert, update, delete) of a has many relation with paper trail and easily revert them? In the end it does not matter to if the related data is attached via json or classic relations at the moment.

**Comment by izelnakri** [comment]
@bumbus yes you track the model that your relationship is based upon. Thanks, closing this issue then
