### ISSUE TITLE
Unclear how to use `PaperTrail.Multi`.

### ISSUE THREAD

**Issue by hickscorp** [izelnakri/paper_trail#128]
We're trying to integrate PaperTrail in our application, which uses Ecto.Multi quite extensively.
We've tried many different combinations of `PaperTrail.Multi.new()`, then adding steps using the standard `Ecto.Multi.insert` and / or `Ecto.Multi.update` functions, then trying to commit using `PaperTrail.Multi.commit` but it doesn't seem to work.
We've noticed that `PaperTrail.Multi.insert` and `PaperTrail.Multi.update` exist, but we are confused on the exposed API here - these two don't expose a "step name" for example - so we're not sure whether they're drop-in replacement or wrappers, and how to use them.

It would be great if someone could indicate how to use `PaperTrail` with `Multi` - or maybe add tests so that we could understand?

So far, the only solution we found would be to replace all our calls to `Multi.update` / `Multi.insert` by `Multi.run` wrapping `PaperTrail.*` equivalents... Is it the way to go?

**Comment by maennchen** [comment]
@hickscorp I don't think that you're currently supposed to call `PaperTrail.Multi` directly. As far as I see the only reason `Multi` is used is to queue both the operation and it's version into one transaction.

I think currently that the modules `PaperTrail.Multi`, `PaperTrail.RepoClient` & `PaperTrail.Serializer` should probably be `@moduledoc false`.

It would however be very useful to refactor `PaperTrail.Multi` a bit so that it also takes a `name` for the operation and can be used directly.

**Comment by hickscorp** [comment]
Good afternoon @maennchen and thanks for the insights. I understand now - `PaperTrail.Multi` is used internally by PaperTrail.

For what it's worth, we've started rolling our own, as a drop-in replacement for Repo.
It might be of interest to you, here is how it works (See snippet).
Essentially, it acts as a "man in the middle" between the repo and the Ecto API.
The reason for this, is that `PaperTrail` architecture fails short if an application has more than one repo, and also requires a refactor of the codebase to:
- 1) Use `PaperTrail.*` instead of `Repo.*`
- 2) Account for the `{:ok, %{model: model, version: version}}` while most of the case the caller doesn't care about it.

It's work in progress (started yesterday), uses PaperTrail internally until we roll our own (Especially around things that cannot be serialised using JSON like binaries), and also have a bit of logic around the problem of "if a record is versioned for the first time, then store its entirety" - otherwise it becomes impossible to use PaperTrail on existing systems with lots of records if we want to be able to reconstruct the state of a given object at any given time - without the initial state we couldn't.

Let me know if interested, happy to post progress.

```
defmodule RepoVersioner do
  defmacro __using__(opts \\ []) do
    quote location: :keep do
      defmodule Impl do
        use Ecto.Repo, unquote(opts)
      end

      @exclude unquote(Keyword.get(opts, :exclude, []))

      @behaviour Ecto.Repo

      defdelegate config(), to: Impl
      defdelegate __adapter__(), to: Impl
      defdelegate start_link(opts \\ []), to: Impl
      defdelegate child_spec(opts), to: Impl
      defdelegate stop(timeout \\ 5000), to: Impl
      defdelegate checkout(fun, opts \\ []), to: Impl
      defdelegate load(schema_or_types, data), to: Impl
      defdelegate get_dynamic_repo(), to: Impl
      defdelegate put_dynamic_repo(dynamic), to: Impl
      defdelegate get(queryable, id, opts \\ []), to: Impl

      defdelegate get!(queryable, id, opts \\ []), to: Impl
      defdelegate get_by(queryable, clauses, opts \\ []), to: Impl
      defdelegate get_by!(queryable, clauses, opts \\ []), to: Impl
      defdelegate one(queryable, opts \\ []), to: Impl
      defdelegate one!(queryable, opts \\ []), to: Impl
      defdelegate all(queryable, opts \\ []), to: Impl
      defdelegate exists?(queryable, opts \\ []), to: Impl
      defdelegate reload(queryable, opts \\ []), to: Impl
      defdelegate reload!(queryable, opts \\ []), to: Impl
      defdelegate preload(struct_or_structs_or_nil, preloads, opts \\ []), to: Impl
      defdelegate stream(queryable, opts \\ []), to: Impl
      defdelegate aggregate(queryable, aggregate, opts_or_field \\ []), to: Impl
      defdelegate aggregate(queryable, aggregate, field, opts), to: Impl
      defdelegate prepare_query(operation, query, opts), to: Impl
      defdelegate default_options(operation), to: Impl

      def insert(struct, opts \\ []),
        do: struct |> maybe_version(opts, &PaperTrail.insert/2, &Impl.insert/2)

      def insert!(struct, opts \\ []),
        do: struct |> maybe_version(opts, &PaperTrail.insert!/2, &Impl.insert!/2)

      def update(struct, opts \\ []),
        do: struct |> maybe_version(opts, &PaperTrail.update/2, &Impl.update/2)

      def update!(struct, opts \\ []),
        do: struct |> maybe_version(opts, &PaperTrail.update!/2, &Impl.update!/2)

      def delete(struct, opts \\ []),
        do: struct |> maybe_version(opts, &PaperTrail.delete/2, &Impl.delete/2)

      def delete!(struct, opts \\ []),
        do: struct |> maybe_version(opts, &PaperTrail.delete!/2, &Impl.delete!/2)

      def delete_all(queryable, opts \\ []),
        do: Impl.delete_all(queryable, opts)

      def insert_or_update(changeset, opts \\ []),
        do: Impl.insert_or_update(changeset, opts)

      def insert_or_update!(changeset, opts \\ []),
        do: Impl.insert_or_update!(changeset, opts)

      def update_all(queryable, updates, opts \\ []),
        do: Impl.update_all(queryable, updates, opts)

      def insert_all(schema_or_source, entries, opts \\ []),
        do: Impl.insert_all(schema_or_source, entries, opts)

      def transaction(fun_or_multi, opts \\ [])

      def transaction(%Ecto.Multi{operations: ops} = multi, opts),
        do: multi |> wrap_multi() |> Impl.transaction(opts)

      defdelegate in_transaction?(), to: Impl
      defdelegate rollback(value), to: Impl

      ## Private.

      def wrap_multi(%Ecto.Multi{operations: ops} = multi),
        do: %{multi | operations: Enum.map(ops, &wrap_operation/1)}

      def wrap_operation({name, {:run, fun}}),
        do: {name, {:run, fn Impl, stuff -> fun.(__MODULE__, stuff) end}}

      def wrap_operation({name, {:changeset, %Ecto.Changeset{action: :insert} = cs, opts}}),
        do: {name, {:run, fn _, _ -> insert(cs, opts) end}}

      def wrap_operation({name, {:changeset, %Ecto.Changeset{action: :update} = cs, opts}}),
        do: {name, {:run, fn _, _ -> update(cs, opts) end}}

      def wrap_operation({name, {:changeset, %Ecto.Changeset{action: :delete} = cs, opts}}),
        do: {name, {:run, fn _, _ -> delete(cs, opts) end}}

      # TODO: We should error here and prevent developers from using this, as we're unable to track versions.
      def wrap_operation({_name, {:update_all, _queryable, _updates, _opts}} = op),
        do: op

      # TODO: We should error here and prevent developers from using this, as we're unable to track versions.
      def wrap_operation({_name, {:merge, fun}} = op),
        do: raise("What")

      # def transaction(fun, opts) when is_function(fun),
      #   do: Impl.transaction(fun, opts)

      # Struct is a changeset, but is excluded.
      defp maybe_version(%Ecto.Changeset{data: %{__struct__: model}} = struct, opts, _, f2)
           when model in @exclude,
           do: struct |> f2.(opts)

      # Struct is a changeset, and is included.
      defp maybe_version(%Ecto.Changeset{} = struct, opts, f1, _),
        do: struct |> f1.(ecto_options: opts) |> paper_trail_unwrap()

      # Struct is a schema instance, but is excluded.
      defp maybe_version(%{__struct__: model} = struct, opts, _, f2)
           when model in @exclude,
           do: struct |> f2.(opts)

      # Struct is a schema instance, and is included.
      defp maybe_version(%{__struct__: _} = struct, opts, f1, _),
        do: struct |> f1.(ecto_options: opts) |> paper_trail_unwrap()

      defp paper_trail_unwrap({:ok, %{model: model}}),
        do: {:ok, model}

      defp paper_trail_unwrap(value),
        do: value
    end
  end
end
```

**Comment by maennchen** [comment]
@hickscorp Oh, that looks very interesting. I'd like to use something like this myself.

If @izelnakri agrees, I think this could be an awesome improvement of this lib.

**Comment by hickscorp** [comment]
In this case, I will post updates. Maybe we can team up :)

**Comment by izelnakri** [comment]
Hi there @maennchen  & @hickscorp, I'm extremely busy these days due to workload, thus would appreciate if you could create a PR with the requested changes. I haven't read all the code here above yet, `PaperTrail.Multi` was built at the time to give more flexibility to developers to customize the transaction `PaperTrail` uses, so I'd be interested in any approaches that could make it more flexible, while keeping the library simple(without complicating it too much). Thanks!

**Comment by maennchen** [comment]
@hickscorp I've spent some time cleaning up #131 and properly exposing `Ecto.Multi` #132 as a first step.

After this I would like to tackle #133. When that is done I think the basis should be complete to provide a clean implementation of what you've posted above :)

**Comment by izelnakri** [comment]
I suppose we can close this issue, please let me know if you'd like it to be re-opened.

**Comment by hickscorp** [comment]
Hi @izelnakri,

Yes, it seems like a good idea to close it for now.
After investigating, we decided to have versioning done outside of our application - too many cases where it's unfortunately not possible to do it at Ecto level.
