### ISSUE TITLE
Multi-Repo Configuration

### ISSUE THREAD

**Issue by maennchen** [izelnakri/paper_trail#133]
Currently all configuration is applied globally. To enable things like #128, this library should be configurable per Repo and not globally.

**Comment by izelnakri** [comment]
Yes, this sounds good!

**Comment by maennchen** [comment]
@izelnakri I think we'll find a way that uses the current config with a deprecation warning.

**Comment by izelnakri** [comment]
Hi @maennchen, given all the changes that occured in `paper_trail` in the last 4.5+ years. I'm not sure if this issue is already resolved or a certain change is needed. 

Could you let me know? I'd like to close the issue otherwise.

**Comment by maennchen** [comment]
@izelnakri A lot has happened here as well, the project moved to a postgres trigger based approach, is no longer used (it was a covid contact tracing application) and I moved on a new company.

We can close this.
