### ISSUE TITLE
Question: Is it possible to insert the version and change the model using 2 steps in the database?

### ISSUE THREAD

**Issue by abravalheri** [izelnakri/paper_trail#137]
Hello, thank you very much for the awesome library!

I was just wondering if it is possible to insert the version record in the database first, and then, in a second stage update the model...
(is there any consistency checks assumptions that the library relies on and that would break?). Have anyone ever tried to do that?

This question might sound weird, but the use case is rather simple: imagine an application that regular users can change a record, but the changes need to be approved by a moderator... (I understand that multiple users proposing changes at the same is problematic, but for the sake of simplicity, let's assume each record belongs to a single user, only the owner can "propose changes", and that owners cannot propose new changes while there are pending changes).

Would it be the case of creating the version using `PaperTrail.make_version_struct`, inserting it to the database via conventional `Repo.insert` and then later (when the change is approved) creating a new changeset for the model using `PaperTrail.Version.item_changes` and updating the model via conventional `Repo.update`?

**Comment by izelnakri** [comment]
Not sure why you'd want that. Seems like your scenario includes 2 different models (Post, PostSuggestion) so they would be tracked differently. It is much better to follow a certain standard/convention rather than to reinvent/change the wheel/introduce a new way/custom deviation in my opinion. What do you think?

**Comment by izelnakri** [comment]
Closing this issue, let me know if you'd like it to be reopened.
