### ISSUE TITLE
Filter Changes

### ISSUE THREAD

**Issue by asummers** [izelnakri/paper_trail#22]
Is there interest in being able to filter certain changes from the changes stored in the DB? Suppose I have a `User` schema. I might not want to version their password hash, for example. This could perhaps be done as a hook in the `make_version_struct` or `serialize` functions. I can see use cases for having filters defined at the schema level, as well as individual inserts/updates, so being able to pass in a list of fields to omit would be ideal. Having `:only`/`:except` opts would be consistent with other Elixir code in the core lib. 

I'm imagining something like like:
 
```
user = User.changeset(%User{}, %{password: "hash", first_name: "John", last_name: "Smith"})
PaperTrail.insert!(user, only: [:first_name, :last_name]) 
PaperTrail.insert!(user, except: [:password])  

defimpl PaperTrail.ChangeFilter.Only, for: User do
  def only(), do: [:first_name, :last_name]
end

defimpl PaperTrail.ChangeFilter.Except, for: User do
  def except(), do: [:password]
end
```

I imagine if both are defined, `only` wins over `except` and the intersection of `defimpl except` opt `except` and the union of `defimpl only` and opt `only`, though I'm not sure how complicated those rules should really be.

**Comment by zachdaniel** [comment]
@andrew I think perhaps just like a `filter` function that takes the whole changes object. that way things can be filtered by value as well.

**Comment by asummers** [comment]
That could work. 

```
defimpl PaperTrail.ChangeFilter.Only, for: User do
  def filter(changeset) do
    changes = Map.drop(changeset.changes, [:password])
    %{changeset | changes: changes}
  end
end

defimpl PaperTrail.ChangeFilter.Only, for: Any do
  def filter(changeset), do: changeset
end
```

**Comment by zachdaniel** [comment]
well, without the `.Only`

**Comment by izelnakri** [comment]
Filtering changes at paper_trail level would create inconsistency for rolling back versions/ reverting back to certain point in history. 

For your password_digest example I think I would still create a version with ```PaperTrail.update()```, perhaps a better example would be forgot_password hashes/requests. You might not want to create a versions for such db changes but then my forgot_password request would go through a specialized changeset that only Ecto casts forgot_password field. Also I wont use ```PaperTrail.update``` for it I think, instead a simple Repo.update.

I deem this feature to be unnecessary unless there are better reasons/examples/use-cases. Thanks for your feature suggestion though, I always like feature suggestions ;)
