### ISSUE TITLE
Nested association tracking after version 0.9.0

### ISSUE THREAD

**Issue by thenick775** [izelnakri/paper_trail#225]
Hello, this is more of a question regarding versioning and nested associations.

Before version `0.10.X` we were able to track nested association changes out of the box, referencing `has_many`/`belongs_to` etc. associations on changesets.

The last successful version this worked for was [0.9.0](https://hex.pm/packages/paper_trail/0.9.0)

Was this an intentional change? I scanned the changelog and was not able to find any information on if removing trails on Ecto associations was done intentionally, or if this is a bug.

I know there was a lot of discussion on nested associations generating/being included in a paper trail, where this does work for embeds.

Any assistance here is appreciated!

**Comment by izelnakri** [comment]
There is currently no support for nested associations and we suggest doing those explicitly updates explicitly in a DB transaction with `Ecto.Multi`. Supporting such feature would increase the complexity of the existing tests tremendously. 

I'm closing this issue, let me know if you'd like it to be reopened.
