### ISSUE TITLE
PaperTrail.Version fields are tagged read_after_write - MySQL does not support

### ISSUE THREAD

**Issue by tjchambers** [izelnakri/paper_trail#228]
getting this error after installing PaperTrail 1.0.0 for first time:

`(ArgumentError) MySQL does not support :read_after_writes in schemas for non-primary keys. The following fields in PaperTrail.Version are tagged as such: [:id, :origin]`

OTP 26 with Elixir 1.15.4 using MySQL via MyXQL

Thoughts on how to avoid this? `:id` I believe IS my primary key.

**Comment by tjchambers** [comment]
After looking closely at the code in this repo I diagnosed I needed to add `origin_read_after_writes: false` to my paper trail config and
`mix dips.compile` for all my environments to get this overridden. I must have missed this in the docs as it is critical OOB for MySQL.

**Comment by izelnakri** [comment]
Feel free to create a PR to update the docs @tjchambers ! Closing this issue now, let me know if this needs to be reopened.
