### ISSUE TITLE
** (RuntimeError) trying to access Mix.Project.app_path for an umbrella project but umbrellas have no app

### ISSUE THREAD

**Issue by seymores** [izelnakri/paper_trail#27]
Using Phoenix 1.3 final and Papertrail 0.7.6.
Got this error when I try to run `mix papertrail.install`.

Must install in the app instead of from the top umbrella project?

```
** (RuntimeError) trying to access Mix.Project.app_path for an umbrella project but umbrellas have no app
```

**Comment by izelnakri** [comment]
This is interesting I will try to create an umbrella project and test this, meanwhile you can fork the repo and create a pull request if you find the fix. Thanks for the report!

**Comment by seymores** [comment]
The problem is that the Mix.Tasks.Papertrail.Install couldn't find out where is "priv/repo/migrations" located.
I looked at how Phoenix is currently handling the situation and it looks way more involved than I thought -- so my immediate solution is to run `mix papertrail.install` in the umbrella's app with the repo and migration files. :-D

I will submit PR if I get this resolved.
