### ISSUE TITLE
Unable to change item_id type

### ISSUE THREAD

**Issue by coladarci** [izelnakri/paper_trail#31]
I've confirmed that my config setting is correct:
```
iex(app-local@127.0.0.1)6> Application.get_env(:paper_trail, :item_type, :integer)
Ecto.UUID
```
I've updated my migration and confirmed that the field is `uuid` in the DB, yet when I try and send one through, I get this error:
```
16:15:07.811 [error] Task #PID<0.1710.0> started from #PID<0.1013.0> terminating
** (Ecto.ChangeError) value `"c7fcaf33-04b1-4e24-b0da-8c38a9cdf3e8"` for `PaperTrail.Version.item_id` in `insert` does not match type :integer
    (ecto) lib/ecto/repo/schema.ex:783: Ecto.Repo.Schema.dump_field!/6
    (ecto) lib/ecto/repo/schema.ex:792: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
    (stdlib) lists.erl:1263: :lists.foldl/3
    (ecto) lib/ecto/repo/schema.ex:790: Ecto.Repo.Schema.dump_fields!/5
    (ecto) lib/ecto/repo/schema.ex:739: Ecto.Repo.Schema.dump_changes!/6
    (ecto) lib/ecto/repo/schema.ex:206: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/multi.ex:422: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/multi.ex:412: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1275: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (paper_trail) lib/paper_trail.ex:152: PaperTrail.update/2
```
Am I missing something? I've restarted my servers, even re-migrated everything from scratch and still getting this.. Thanks! 

FYI - I'm using Ecto 2.2.1 + Paper Trail 0.7.7 and this is being used inside an umbrella app. My guess is the latter might have something to do with it?

**Comment by izelnakri** [comment]
Hi, I'm not sure what the problem here. Please check your table schemas from the postgres console(\d+ table_name should give the definition). Make sure your migration references and model schema definitions in each model are correctly defined. Lastly, please note that you cannot use UUID and integer type at the same time in your application for different model versions.

Perhaps this is a bug but we have a wide test coverage so I don't think so, I might be wrong. Feel free to provide more specifications, thanks again for your report.

**Comment by coladarci** [comment]
![image](https://user-images.githubusercontent.com/1004167/31060406-0f8c46de-a6c8-11e7-93a1-9705f90f2c79.png)

Hey @izelnakri - thanks for the response. I started from scratch and ran into the same issue. The above is data you asked for. 

I noticed that your badge indicates failing tests - I checked and the failing tests also happen to deal very similar issues. Do you mind double checking? Thanks!

**Comment by doughsay** [comment]
@izelnakri please see the above comment.  You're tests have been failing for 5 months.  Having wide test coverage is great, but not if they're failing and you seem to not care about fixing them...
https://circleci.com/gh/izelnakri/paper_trail

**Comment by izelnakri** [comment]
@doughsay you are more than welcome to fix the CircleCI issue. Have you ever tried to run the tests locally? They pass, there is something wrong with the CircleCI setup/runtime. 

Please be more constructive next time. I always read and review pull requests, this is the reason the current pending PRs that lack the certain standard dont get a pass.

**Comment by doughsay** [comment]
@izelnakri sorry if I came off a bit harsh.  We did in fact get things working on our end.

I wasn't aware that the tests failing were related to CircleCI only, so the (erroneous) assumption was that the failing tests regarding UUIDs was related to our inability to get it working with UUIDs.  The coincidence was suspicious.

@coladarci you can go ahead and close this issue, since we got it working.

**Comment by coladarci** [comment]
To be fair, my setup still doesn't work.. :) ..but the fact that you pulled the exact same code and didn't have a problem clearly points to something on my end, not the projects. Thanks all.....

**Comment by johnhamelink** [comment]
I had this issue, but after running `mix deps.update paper_trail`, Ecto was updated from 2.2.7 to 2.2.8 and db_connection was updated from 1.1.2 to 1.1.3 which seemed to make this problem go away.

**Comment by devvit** [comment]
```PaperTrail.Version``` is outside your project, remove  ```_build``` directory, recomopile all

**Comment by romariolopezc** [comment]
Hello, just installed PaperTrail and configured it and ran into the same issue:

Config:
```
config :paper_trail,
  repo: Tiketeo.Repo,
  item_type: Ecto.UUID,
  originator_type: Ecto.UUID,
  originator_relationship_options: [references: :uuid],
  originator: [name: :user, model: Tiketeo.Accounts.User],
  timestamps_type: :utc_datetime_usec
```

```
iex(7)> Application.get_env(:paper_trail, :item_type, :integer)
Ecto.UUID
```

Table in psql:
```
tiketeo_dev=# \d+ versions
                                               Table "public.versions"
    Column     |            Type             | Collation | Nullable | Default | Storage  | Stats target | Description
---------------+-----------------------------+-----------+----------+---------+----------+--------------+-------------
 id            | uuid                        |           | not null |         | plain    |              |
 event         | character varying(10)       |           | not null |         | extended |              |
 item_type     | character varying(255)      |           | not null |         | extended |              |
 item_id       | uuid                        |           |          |         | plain    |              |
 item_changes  | jsonb                       |           | not null |         | extended |              |
 originator_id | uuid                        |           | not null |         | plain    |              |
 origin        | character varying(50)       |           |          |         | extended |              |
 meta          | jsonb                       |           |          |         | extended |              |
 inserted_at   | timestamp without time zone |           | not null |         | plain    |              |
Indexes:
    "versions_pkey" PRIMARY KEY, btree (id)
    "versions_event_item_type_index" btree (event, item_type)
    "versions_item_id_item_type_index" btree (item_id, item_type)
    "versions_item_type_inserted_at_index" btree (item_type, inserted_at)
    "versions_originator_id_index" btree (originator_id)
Foreign-key constraints:
    "versions_originator_id_fkey" FOREIGN KEY (originator_id) REFERENCES users(id)
Access method: heap
```

Seems that everything is UUID but something is wrong?

@doughsay how did you fix it?

**Comment by doughsay** [comment]
That was 4 years ago, and many versions ago, I don't remember, and we do not use papertrail anymore.

**Comment by romariolopezc** [comment]
I solved by removing the compiled `_build/` papertrail folder, recompiled and ir worked :man_shrugging:
