### ISSUE TITLE
Equivalent of Repo.insert options for "on_conflict: :replace_all, conflict_target:"

### ISSUE THREAD

**Issue by seymores** [izelnakri/paper_trail#32]
I have a need to use the `on_conflict` option, but I think PaperTrail is not supporting yet.
My insert with option looks like below.
Is there something equivalent I can use in PaperTrail for this?

```
Repo.insert(on_conflict: :replace_all, conflict_target: :item_id)
```

**Comment by izelnakri** [comment]
I probably need to see the implementation with test cases to understand what is actually missing and could be implemented.

I'm looking forward to your pull request if this is bugging you. Thanks.

**Comment by izelnakri** [comment]
I've just closed this issue since there is no specifications. I'm willing to reopen it when its specified.
