### ISSUE TITLE
Allow Model ID column to be configurable.

### ISSUE THREAD

**Issue by jalcine** [izelnakri/paper_trail#33]
I use UUIDs for my models with PostgreSQL (though the database layer shouldn't matter here). At [this point](https://github.com/izelnakri/paper_trail/blob/0e978bf6e066802bcbbe1dc0a546a0c92d6b2052/lib/paper_trail.ex#L239) in the insert bits, it looks like it's hardcoded to use `id` as the attribute.

I'm proposing to have a `id_column` configuration option that allows for specifying this.

Side-note: this looks like a prime spot for some refactoring re: how that Version struct is built!

**Comment by izelnakri** [comment]
We already have this feature, please check the documentation and you're welcome to issue a pull request for any refactors. 

When I built this library it was very simple and in many ways it is still quite straightforward and stable in general(have many tests). In case if you are interested in refactoring and create a pull request I will make sure I will review it objectively, I don't hold any emotions against code.
