### ISSUE TITLE
Is it possible to delay inserting versions while seeding data?

### ISSUE THREAD

**Issue by mirelon** [izelnakri/paper_trail#34]
I have seeds, which are inserting lot of various data into DB.

Profiling shows that lot of time is spent inserting paper_trail versions.

Is it possible to postpone inserting paper_trail versions to the end of seeding? And then insert all versions in one batch?

**Comment by izelnakri** [comment]
If anyone wants to implement batch operations(PaperTrail.insert_all, PaperTrail.update_all and PaperTrail.delete_all methods) I'm more than happy to review it, currently I don't need such a feature so I haven't implemented it nor any of the contributors.

I do understand its usefulness and I'm in favor it in case if you like to build it and create a pull request.

**Comment by izelnakri** [comment]
Related to: https://github.com/izelnakri/paper_trail/issues/4
