### ISSUE TITLE
Originator relationship not working

### ISSUE THREAD

**Issue by digitalcake** [izelnakri/paper_trail#36]
I can see that I'm storing the originator_id and I have the config set to use "user" correct as I can use the name user for the origininator

IE ` |> PaperTrail.insert(user: user)` and again I can see the id being set correctly in the db. 

But when I try to preload or call upon the originator thats where I hit a problem. 

```

{:ok, results} = cs |> PaperTrail.insert(user: user)

version = results[:version]

version |> IO.inspect
 --->
%PaperTrail.Version{
  __meta__: #Ecto.Schema.Metadata<:loaded, "versions">,
  event: "insert",
  id: 12,
  inserted_at: ~N[2018-02-14 19:12:08.399937],
  item_changes: %{
   ...
  },
  item_id: 31,
  item_type: "Client",
  meta: nil,
  origin: nil,
  originator_id: 1
}

version.user
** (KeyError) key :user not found in: %PaperTrail.Version{...}

version.originator
** (KeyError) key :originator not found in: %PaperTrail.Version{...}

version.originator_id
--> 1

version |> Repo.preload(:user)
** (ArgumentError) schema PaperTrail.Version does not have association :user

version |> Beffect.Repo.preload(:originator)
** (ArgumentError) schema PaperTrail.Version does not have association :originator

```

Not sure what I'm missing here. 

Spec:
* Elixir 1.6.0
* Phoenix 1.3
* ecto 2.2.8
* paper_trail 0.7.7

**Comment by digitalcake** [comment]
It would look as if define_field is false for the Ecto Schema. 
https://github.com/izelnakri/paper_trail/blob/master/lib/version.ex#L24

Why is that? and would would I define that field otherwise?

**Comment by digitalcake** [comment]
Nope I was wrong its the condition that is preventing the belongs to. 
https://github.com/izelnakri/paper_trail/blob/master/lib/version.ex#L21

I removed the condition locally and I no longer have an issue, but its odd because if I run the condition it looks as if it should render true. So I don't know why the condition is failing to set the belongs_to correctly.

**Comment by digitalcake** [comment]
Ok, I think I may have found the issue, the deps compiled before I added config but then they didnt recompile. Since you will need to recompile the deps after you update the config/config it maybe worth noting in the READ ME.

**Comment by izelnakri** [comment]
I'm glad that you've found this issue and included in your pull request. I will review and merge it to README.
