### ISSUE TITLE
Feature Request: Versions for nested associated records. 

### ISSUE THREAD

**Issue by joshchernoff** [izelnakri/paper_trail#39]
If I insert a changeset that contains other associated structs only the parent gets recorded in the versions table. 

All the other nested records are disregard. 

This currently occurs at 
https://github.com/izelnakri/paper_trail/blob/master/lib/paper_trail.ex#L296

And it only happens for the insert. 

Updates will cause an error related to #38 

I think we should loop over the changeset and create a version for each ecto changeset found.

**Comment by izelnakri** [comment]
Yes, I agree this behavior should change. 

We should either raise or implemented nested version tracking. 

Although I'm not in favor of a nested versioning feature I've always been open to review and if it is good and community wants it, merge the feature. So far there has been 3 trials however none were able to finish and test the feature completely.

**Comment by fv316** [comment]
Has there been any progress on this? I see it has been closed without a solution.

**Comment by izelnakri** [comment]
Hi @fv316, no solution so far has been complete for a review and I'm not going to implement it personally. Feel free to take a stab at if you like like. I'd be willing to review however the final solution should be well covered with tests without having detrimental effect on the rest of the source code ideally.

**Comment by joshchernoff** [comment]
This feature request was asking it to look at it from a design perspective. It's fair to say this is a very hard ask. There is little incentive to dev out said feature unless there is a solid consensus on the design change if that comes at the expense of other patterns put in place.  I can't see a clear additive approach to this. Maybe more open discussion is required?

**Comment by joshchernoff** [comment]
Also closing the ticket does even less to help promote the idea if you really are up for seeing it. Just saying 🤷‍♂️
