### ISSUE TITLE
Make table name configurable.

### ISSUE THREAD

**Issue by steffenix** [izelnakri/paper_trail#43]
I would like to use paper_trail but my database already has a table named version, we could make the table name configurable.
What do you think @izelnakri ?

**Comment by izelnakri** [comment]
Sure @steffenix, writing tests for such scenario could be challenging but I always welcome pull requests to this project.

**Comment by steffenix** [comment]
I have made changes but like you said it's hard to make the tests

**Comment by izelnakri** [comment]
we can make one simple test and if there are edge cases we can add the other tests later. Looking forward to your pull request!
