### ISSUE TITLE
MySQL does not support read_after_write

### ISSUE THREAD

**Issue by kalvinhom-fluxx** [izelnakri/paper_trail#44]
https://github.com/izelnakri/paper_trail/blob/113ff97d8283c80d24ca4aea53fe1d763f5ab5ac/lib/version.ex#L17

MySQL fails on insert because it doesn't support read_after_write.  It doesn't seem like this is really required here?

**Comment by izelnakri** [comment]
I don't want to support MySQL. Feel free to fork to project if you want to create a versioning library for MySQL. I'm sorry.
