### ISSUE TITLE
Elixir 1.6.5 - Compilation warnings result in "module Papertrail is not available"

### ISSUE THREAD

**Issue by travcunn** [izelnakri/paper_trail#45]
When compiling my app, I see these warnings:
```==> paper_trail
Compiling 5 files (.ex)
warning: clauses for the same def should be grouped together, def get_version/2 was previously defined (lib/paper_trail/version_queries.ex:61)
  lib/paper_trail/version_queries.ex:90

warning: function MyApp.Repo.all/1 is undefined (module MyApp.Repo is not available)
Found at 2 locations:
  lib/paper_trail/version_queries.ex:32
  lib/paper_trail/version_queries.ex:48

warning: function MyApp.Repo.get/2 is undefined (module MyApp.Repo is not available)
  lib/paper_trail/version_queries.ex:99

warning: function MyApp.Repo.one/1 is undefined (module MyApp.Repo is not available)
Found at 2 locations:
  lib/paper_trail/version_queries.ex:76
  lib/paper_trail/version_queries.ex:92
```

Finally, when attempting to use Papertrail in my app, I get the following error: 
```
** (UndefinedFunctionError) function Papertrail.insert/2 is undefined (module Papertrail is not available)
```

Note; `MyApp` is a placeholder for what my app is actually called.

Am I missing something obvious?

paper_trail == 0.7.7
ecto == 2.2.8
postgrex == 0.13.5

elixir 1.6.5

**Comment by travcunn** [comment]
Ok it looks like https://github.com/seymores/paper_trail is another fork of this repo that works correctly in my environment. Could it just be a difference between Elixir versions that are supported?

**Comment by mindreframer** [comment]
@travcunn you should update your paper_trail version to `0.8`. The readme is not up-to-date.

**Comment by izelnakri** [comment]
Yes, also the module name is PaperTrail not Papertrail. Im closing this issue now. Let me know if you would like it reopened.

**Comment by travcunn** [comment]
Thanks for the responses. I made a really stupid mistake and tried to use the `Papertrail` module rather than the `PaperTrail` module.

I thought I was going crazy, turns out I need to pay more attention to details.
