### ISSUE TITLE
[Feature Request / Looking for Solution] How to utilize Ecto's Multi + Create Version

### ISSUE THREAD

**Issue by stonehz** [izelnakri/paper_trail#48]
We are trying to find a way on how to wrap multiple updates on a transaction + build the version  but not sure what would be the right approach.
We have the following scenario: 

> I have a user and address schema. 
> A user may have many addresses. 
> When someone updates their address, i would also like to update the user's 'last_updated_at' date field (in the user table).
> We currently have wrapped both updates on a Multi and they will be executed in a transaction.
> Now we want to introduce versioning on the User Model but we see 1-2 ways that can be done:

1) Get access to private function `make_version_struct` (https://github.com/izelnakri/paper_trail/blob/master/lib/paper_trail.ex#L295 )  and add it on our existing multi (bypassing all other  paper_trail logic which  can not guarantee future-compatibility)
2) Implement something like `PaperTrail.multi`? (that means that we need to provide which changesets are to be stored as versions or if the whole thing will be treated as one, etc)

**Comment by izelnakri** [comment]
Feel free to submit a pull request, I'm interested in the second approach!
