### ISSUE TITLE
Version originator relationships

### ISSUE THREAD

**Issue by mymai91** [izelnakri/paper_trail#49]
This is the documentation
# in your config/config.exs

```  
config :paper_trail, originator: [name: :user, model: YourApp.User]
```
Let's say my model is App.Account.User
I need to config

```  
config :paper_trail, originator: [name: :user, model: App.Account.User]
```
Technically, It should get the association with `User` but It got `Account`. 
To make it work, I have to create one more model with the name `App.User` but I don't think this is a good way.

Can you help take a look at it? 

Thanks for your supporting

**Comment by izelnakri** [comment]
Hi, 

Which table do you have a foreign key relationships with in your postgres database? You can check it with `$ psql your_database_name` and then `\d+ versions`. 

If you change your originator model you need to first create a database migration so the columns foreign key reference is different. Did you make that change?

**Comment by mymai91** [comment]
hi @izelnakri 

Table have a foreign key relationships is `users` but the model name for this table is `App.Account.User` not `App.User`

I double check like your way but still can't fix.

Config
```
# Config Elixir Paper trail
config :paper_trail,
repo: App.Repo,
originator: [name: :user, model: App.Account.User]
```

Error: `protocol Ecto.Queryable not implemented for App.Account.User, the given module does not exist.`

**Comment by izelnakri** [comment]
I will need more specifications unfortunately to reproduce the bug. 

Could you create a showcase phoenix application with the bug and link it here? Then I can understand the true issue and we can create fix and tests cases accordingly.

**Comment by mymai91** [comment]
@izelnakri i just read your feedback. I will do it asap. maybe tomorrow.
Thanks for supporting
