### ISSUE TITLE
Update Changelog

### ISSUE THREAD

**Issue by mstratman** [izelnakri/paper_trail#54]
A Changelog is crucial for assessing whether to upgrade, and what changes might be required in a user's codebase to facilitate the upgrade.

Ideally under each version it will categorize the types of changes:
* Enhancements
* Changes
* Bug fixes
* Deprecations
* Breaking changes

**Comment by mstratman** [comment]
I may take a first stab at this, and just took a look and saw tags aren't being used for releases. I recommend tagging each release to have a clear and convenient-to-access way of identifying the point in time of a particular version. It adds very little time to the workflow.

Using commit messages or tracking changes to mix.exs - which is what it appears I'd need to look at here? - is brittle and more difficult to navigate in my experience.

Love the module by the way! Thanks for all the great work on it!

**Comment by izelnakri** [comment]
Hi Mark! Thanks for your appreciation. Yes I've only version taged the last release, and will always tag versions from now on.

Feel free to read the commit history, I hope it will be enough to generate a changelog, I'll be keeping a changelog from now on. Looking forward to your PR ;)
