### ISSUE TITLE
Tracking current_version_id in item_changes seems superfluous.

### ISSUE THREAD

**Issue by bezborodow** [izelnakri/paper_trail#56]
Tracking `current_version_id` in `item_changes` seems superfluous. It is best in many circumstances to deal with a dataset that only highlights what actually changed. Particularly if trying to building a history or timeline of changes to a record in the UI or comparing versions of a record. Having metadata such as `current_version_id` can be tiresome, since it needs to be filtered out.

It is also not particularly useful as it is just a reference to itself and can be inferred from `versions.id` in any case.

![image](https://user-images.githubusercontent.com/950634/60275397-03f3b680-9939-11e9-84a9-4bb4802f098a.png)

```
item_changes:
{
    "user_id": 2,             <-- the actual change
    "current_version_id": 5   <-- superfluous
}
```

**Comment by bezborodow** [comment]
Sort of related, but not quite: #52

**Comment by izelnakri** [comment]
`$model.current_version_id` and `$model.first_version_id` is for the `strict_mode` configuration.

I see that `user_id` of your model gets changes, so `item_changes` for the version of that `PaperTrail.update()` is neccessary.  Having a change in your model means there will be another `PaperTrail.Version`, and that version with have a new `current_version` reference. 

We want to keep each model change have a different `%PaperTrail.Version{}` and make sure there is an immutable trail of all changes/versions so developers can rollback to a certain point in time or can get a models state in anytime in history.

Let me know if you have a better suggestion to handle this problem and thanks for raising this issue!

**Comment by bezborodow** [comment]
Thank you for your considered response.

Personally, I am using versions as merely a history log with no need to roll back. However, from what you said, I can see how some users may need the `current_version_id` field for rolling back, which I did not consider before. But then, that also raises the question: when rolling back to an earlier version, would the `current_version_id` be incremented to a new value if inserting a new row into versions? In this case, it would not be useful because the `current_version_id` would be discarded. In any case, the `current_version_id` can be implied from the `versions.id` field, which is the same (at least in usual circumstances.)

Perhaps the best solution, would be to let the user decide for themselves if any fields should be ignored, as in #52.

**Comment by izelnakri** [comment]
Hi @bezborodow, sorry for late response. Yes it could be possible yet if we let the users decide for themselves it makes the library and tests more complex so I prefer not to implement it unless there is a significant need. I'm closing this issue, feel free to open a new issue if you think this is an important concern
