### ISSUE TITLE
Using PaperTrail with EctoConditionals (Interoperability)

### ISSUE THREAD

**Issue by bezborodow** [izelnakri/paper_trail#57]
I am using PaperTrail to track versioning in conjunction with EctoConditionals.

https://hex.pm/packages/ecto_conditionals
https://github.com/codeanpeace/ecto_conditionals

The documentation mentions that a Repo should be passed in:

```
use EctoConditionals, repo: MyApp.Repo
```

This allows calls such as:

```
%User{id: 1, name: "Flamel"} |> find_or_create
#=> {:ok, %User{id: 1, name: "Flamel"}}
```

The only problem is that this will not call `PaperTrail.insert!/1`.

I managed to workaround this by creating a delegator module and passing it into EctoConditionals as below:

```
use EctoConditionals, repo: PaperTrail.Delegator
```

This then forwards function calls to PaperTrail. Here is the code:

```
defmodule PaperTrail.Delegator do
  defdelegate get_version(record), to: PaperTrail.VersionQueries
  defdelegate get_version(model_or_record, id_or_options), to: PaperTrail.VersionQueries
  defdelegate get_version(model, id, options), to: PaperTrail.VersionQueries
  defdelegate get_versions(record), to: PaperTrail.VersionQueries
  defdelegate get_versions(model_or_record, id_or_options), to: PaperTrail.VersionQueries
  defdelegate get_versions(model, id, options), to: PaperTrail.VersionQueries
  defdelegate get_current_model(version), to: PaperTrail.VersionQueries

  defdelegate insert(changeset, options \\ [origin: nil, meta: nil, originator: nil, prefix: nil]), to: PaperTrail
  defdelegate insert!(changeset, options \\ [origin: nil, meta: nil, originator: nil, prefix: nil]), to: PaperTrail
  defdelegate update(changeset, options \\ [origin: nil, meta: nil, originator: nil, prefix: nil]), to: PaperTrail
  defdelegate update!(changeset, options \\ [origin: nil, meta: nil, originator: nil, prefix: nil]), to: PaperTrail
  defdelegate delete(struct, options \\ [origin: nil, meta: nil, originator: nil, prefix: nil]), to: PaperTrail
  defdelegate delete!(struct, options \\ [origin: nil, meta: nil, originator: nil, prefix: nil]), to: PaperTrail
  defdelegate get_model_id(model), to: PaperTrail

  defdelegate get_by(queryable, clauses, opts \\ []), to: MyApp.Repo
  defdelegate get_by!(queryable, clauses, opts \\ []), to: MyApp.Repo
  defdelegate get(queryable, id, opts \\ []), to: MyApp.Repo
  defdelegate get!(queryable, id, opts \\ []), to: MyApp.Repo
end
```

Please note that the delegate list is incomplete,. It would also need to respect the `@repo` configuration specified in `config/config.exs`. I can make a pull request with this functionality if you would like.

I am not sure if this is a good solution or not, so I would appreciate any feedback. It seems a little bit hacky to me, but it worked in my situation. It may be worth also raising this issue with the author of EctoConditionals to share ideas on how to approach interoperability issues between helper libraries such as that.

**Comment by bezborodow** [comment]
It might even be simpler just to declare the `defdelegate get_by`, etc directly inside the `PaperTrail` module instead of using a `Delegator`. I just did that because it would be easier since I didn't want to modify project dependencies.

**Comment by bezborodow** [comment]
I also noticed that `PaperTrail.insert/1`  will return something like `{:ok, %{model: %Model{ ... }, version: %PaperTrail.Version{ ... }}`, whereas `get_by/3` would just return `{:ok, %Model{ ... }}`.

Therefore my solution is not quite complete without also providing a consistent interface in both circumstances.

I'll work on a pull request soon with some examples to prove what the issue is.

**Comment by izelnakri** [comment]
Hi @bezborodow, thank you for raising these interesting points. 

For the first delegation solution you did I cant think of a better solution for now instead, your solution is fine despite the fact that it might feel hacky, do you have any suggestions?

For your second point:

```exs
      model = case find_or_create_by(model, [:job_id, :node_id]) do
        {:ok, %{model: model}} -> model
        {:ok, model} -> model
      end
```
I do not think this is hacky. In my opinion, it is good that paper_trail provides both model and version in a struct upon insert. That query is also `returning`, thus removes the need for additional query when associated version is needed. 

Thanks again for raising these points/interesting scenarios, if you have any further suggestions please let me know, we can discuss.
