### ISSUE TITLE
Allow strict_mode on a per-model basis

### ISSUE THREAD

**Issue by tensiondriven** [izelnakri/paper_trail#61]
I have an application where I need to use Strict Mode for a certain set of models, but not for all models.  I would like to be able to specify if a model should be treated as "strict", or optionally if a model does not have the `first_version_id` and `current_version_id` fields, it should not be treated as strict.  Currently if a model does not have these fields, it throws:

```
     ** (ArgumentError) unknown field `current_version_id` in ...
```

During an insert.

(For now, I may just add these fields to all my models as `null: false`.)

**Comment by izelnakri** [comment]
I think this is a good design choice, if a model is tracked we want to guarantee its tracked version to always exist. For optional use otherwise, a model could be separated into two tables/models.
