### ISSUE TITLE
Can I use Papertrail.Multi.insert with Enum.reduce?

### ISSUE THREAD

**Issue by rschooley** [izelnakri/paper_trail#67]
The Readme for the project says it's cool to ask questions in a new GH Issue; if you'd prefer this on a forum instead let me know.

I refactored my code from a `Repo.insert_all` to `Enum.reduce -> Ecto.Multi.insert` so I can move it to Papertrail to track the inserts.  This works:

```
{:ok, inserted} =
  Enum.reduce(foos_attrs, Ecto.Multi.new(), fn attrs, multi ->
    Ecto.Multi.insert(
      multi,
      {:foo, foo.id},
      Foo.changeset(%Foo{}, attrs)
    )
  end)
  |> Repo.transaction()
```

But it looks like [PaperTrail.Multi.insert/3](https://hexdocs.pm/paper_trail/PaperTrail.Multi.html#insert/3) doesn't take a `name` argument like [Ecto.Multi.insert/4](https://hexdocs.pm/ecto/Ecto.Multi.html#insert/4) does.

This results in the error:
`** (RuntimeError) :model is already a member of the Ecto.Multi:`

when doing this in the `reduce`:
```
PaperTrail.Multi.insert(
  multi,
  Foo.changeset(%Foo{}, attrs)
)
```

Is there another way to do this that I missed?  Thanks.

**Comment by izelnakri** [comment]
Hi @rschooley, I would actually like to have Repo.insert_all, delete_all and update_all functions just like Repo. If you would like to implement and tests these features please create a PR, I'm currently busy to implement them for a while but would be willing to review and merge a PR. 

As for your question, I'll do an investigation shortly later and come back to you, just saw your issue now. Thanks for bringing it up.

**Comment by marioimr** [comment]
@rschooley I just made a PR because I had your same use case

**Comment by izelnakri** [comment]
Hi @rschooley, your feature request is delivered on new v0.8.7. Closing this issue now, please let me know if you would like to reopen it. Thanks.
