### ISSUE TITLE
Any way to override `version` model?

### ISSUE THREAD

**Issue by asiniy** [izelnakri/paper_trail#8]
I want to change timestamps in `PaperTrail.Version` to make them using an `timex_ecto` field. Is there any way to do that?

**Comment by izelnakri** [comment]
currently paper_trail uses the default ecto timestamps. The assignments happen via ecto, I think the best way to implement that behavior would be to write your own wrapper function inside the papertrail.version model. something like ```PaperTrail.Version.in_timex(version)```, this function can parse and turn those fields to timex fields and return a new struct.

**Comment by asiniy** [comment]
@izelnakri so ditry!

**Comment by izelnakri** [comment]
If you have any API suggestions feel free to provide it here.

**Comment by asiniy** [comment]
@izelnakri to be honest, I don't feel good around the whole structure overall. But `paper_trail` works, and works well, so thanks you for it!

I'm not familiar with FP a lot, I'll suggest when read fundamental books about it. So, give me couple of months :smile:
