### ISSUE TITLE
Initialise already existing records

### ISSUE THREAD

**Issue by marioimr** [izelnakri/paper_trail#91]
Hi, would you accept a PR for creating an entry in the version table for records that have been inserted without paper_trail?

My use case is that I have many records that were inserted before we adopted your library, now I would like to be able to track future changes so I was thinking of creating PaperTrail.initialise/2 function and apply it to all existing records.

**Comment by izelnakri** [comment]
Hi @marioimr, this is an interesting use case, generally I thought you could just ```PaperTrail.Version{} |> Repo.insert``` with "insert" on the versions but I'm always interested in reading and reviewing PRs, so I am looking forward to your PR ;)

**Comment by marioimr** [comment]
My idea was to have a more "complete" API, but on second thought it's not so useful, so I'll close this

**Comment by patmaddox** [comment]
Here's a backfiller we wrote for our app:

```elixir
defmodule OurApp.Tasks.BackfillPapertrailVersions do
  alias OurApp.Repo
  alias OurApp.Service
  import Ecto.Query

  def run do
    Repo.transaction(fn ->
      backfill_model(Service.Person, "Person", [:data, :name_first, :name_last])
      backfill_model(Service.Case, "Case", [:data, :person_id])
      backfill_model(Service.Result, "Result", [:data, :case_id])
    end)
  end

  def backfill_model(struct_type, item_type, fields) do
    from(struct_type)
    |> Repo.stream()
    |> Enum.each(fn record ->
      %PaperTrail.Version{
        event: "insert",
        item_type: item_type,
        item_id: record.id,
        item_changes: Map.take(record, fields ++ [:id, :inserted_at, :updated_at]),
        origin: "backfill"
      }
      |> Repo.insert()
    end)
  end
end
```
